#!/usr/bin/env bash

########################################################################################################################
# SPDX-FileCopyrightText: 2016-2025 Noble Factor
# SPDX-License-Identifier: MIT
########################################################################################################################

# Test-ShellFormatting - Check shell formatting with shfmt
# shellcheck source=../bin/Declare-BashScript

source "$(dirname "$0")/../bin/Declare-BashScript" "$0" "help" "h" "$@"

###########
# Arguments
###########

declare -r synopsis="Test-ShellFormatting [--help]"
eval set -- "$script_arguments"

while :; do
    case $1 in
    -h | --help)
        usage "$synopsis"
        shift 1
        ;;
    --)
        shift 1
        break
        ;;
    *)
        error 2 "Unrecognized option: $1"
        ;;
    esac
done

###########
# Main
###########

note "==> Looking for shell scripts..."

mapfile -t files < <(find bin test webhook.config -type f -exec grep -lE '^#!(/usr/bin/env[[:space:]]+)?(sh|bash)' {} + 2>/dev/null || true)

if [[ ${#files[@]} -eq 0 ]]; then
    note "No shell scripts found."
    exit 0
fi

note "Found ${#files[*]} shell scripts."

note "==> Checking shell formatting..."

if ! shfmt -d -i 4 "${files[@]}"; then
    error 1 "shfmt detected formatting issues. Run 'make format' locally."
fi

success "Formatting check passed on ${#files[@]} files:"
printf '  %s\n' "${files[@]}"
