# Hadolint configuration
#
# Allow DL3059 (pre-FROM ARG flagged as redundant) when used intentionally to
# support BuildKit / buildx multi-platform workflows. Keep explanations wrapped
# to 120 columns or less so repository guidelines and tooling remain readable.

# Hadolint configuration
#
# Allow DL3059 (pre-FROM ARG flagged as redundant) when used intentionally to
# support BuildKit / buildx multi-platform workflows. Keep explanations wrapped
# to 120 columns or less so repository guidelines and tooling remain readable.
ignored:
  - DL3059
