.TH Install-Rclone 1 "October 2025" "docker-homebridge" "User Commands"
.SH NAME
Install-Rclone \- Install the latest Rclone release
.SH SYNOPSIS
Install-Rclone
.SH DESCRIPTION
Downloads and installs the latest Rclone binary, sets up man page, and enables mount commands. Removes older rclone if present.
.SH USAGE
sudo ./Install-Rclone
.SH AUTHOR
NobleFactor