#!/bin/bash

set -o errexit -o nounset -o pipefail -o xtrace

declare -r authorized_key="${1:-}"

if [[ -z ${authorized_key:-} ]]; then
    echo "Error: A non-blank value for authorized_key is required." >&2
    exit 2
fi

declare -r user=webhook-executor-destination
declare -r home=$(getent passwd ${user} | cut -d: -f6)

# Authorize the key

mkdir -p "${home}/.ssh" && echo "${authorized_key:-}" > ${home}/.ssh/authorized_keys
chown -R ${user}:${user} "${home}/.ssh"
chmod 600 "${home}/.ssh/authorized_keys"
chmod 700 "${home}/.ssh"

exec /usr/sbin/sshd -D