#!/bin/bash
set -e

KEY_PATH="/usr/local/etc/webhook/ssh/id_rsa.pub"

if [ ! -f "$KEY_PATH" ]; then
    echo "Error: Public key not found at $KEY_PATH"
    exit 1
fi

# Authorize the key

cp "$KEY_PATH" /home/web-executor-destination/.ssh/authorized_keys
chown -R web-executor-destination:web-executor-destination /home/web-executor-destination/.ssh
chmod 600 /home/web-executor-destination/.ssh/authorized_keys
chmod 700 /home/web-executor-destination/.ssh

exec /usr/sbin/sshd -D